modelparams:
  in_channels: 3
  in_h: 50
  in_w: 200
modelname: "test_model"
optim: "Adam"
lr: 0.003
device: cpu
epochs: 10
test_size: 0.3
test_batch_size: 32
train_batch_size: 32
use_cache: True
clip_grad: 0.1